name: 'app-build-release-publish'

on:
  pull_request:
    branches:
      - main
    paths:
      - 'apps/app/**'
      - '.github/workflows/app-build-release-publish.yml'
  push:
    branches:
      - main
    paths:
      - 'apps/app/**'
      - '.github/workflows/app-build-release-publish.yml'
  workflow_dispatch:

jobs:
  publish-app-release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest' # for Intel based macs.
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'ubuntu-22.04-arm'
            args: ''
          - platform: 'windows-2022'
            args: ''
          - platform: 'windows-11-arm'
            args: ''
          - platform: 'ubuntu-22.04'
            args: '--apk --split-per-abi --target aarch64 --target armv7'
            mobile: 'android'
    uses: ./.github/workflows/app-build.yml
    with:
      build-mode: 'release'
      publish: true
      environment: 'production'
      platform: ${{ matrix.platform }}
      args: ${{ matrix.args }}
      mobile: ${{ matrix.mobile || '' }}
    secrets: inherit
