name: 'site-deploy'

on:
  push:
    branches: [main]
    paths:
      - 'apps/site-*/**'
      - '.github/workflows/site-deploy.yml'

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v5

      - uses: oven-sh/setup-bun@v2

      - run: bun i

      - name: Build & Merge
        run: |
          mkdir out
          for d in apps/site-*/; do
            app=$(basename "$d")
            echo "Building $app..."
            
            cd "$d"
            bun run build
            path=$(grep "base:" astro.config.mjs | sed -E "s/.*base:\s*['\"]Cherit\/?([^'\"]*)['\"].*/\1/" | tr -d /)
            
            mkdir -p "../../out/$path"
            cp -r dist/* "../../out/$path/"
            cd ../..
          done
        env:
          GH_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - uses: actions/upload-pages-artifact@v3
        with:
          path: out

  deploy:
    needs: build
    runs-on: ubuntu-slim
    environment:
      name: github-pages
      url: '${{ steps.deployment.outputs.page_url }}'
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
